# Generated by Django 3.0.5 on 2020-05-14 10:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200506_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verification_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
