# Generated by Django 3.0.5 on 2020-05-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_userprofile_verification_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
